### PR TITLE
Removed superfluous theme files

### PR DESCRIPTION
**Pull request by ryanvergel**

### CODE REVIEW

**Comment by duthv-amd** [comment]
@ryanvergel  what is the difference between this one and PR #58

**Comment by duthv-amd** [comment]
Dup of #58

**Comment by ryanvergel** [comment]
@duthv-amd different PRs for each branch, essentially.

v1.0, v.1.5, v2.0

**Comment by duthv-amd** [comment]
@NastoohX  can we get this merged in for all the branches?

**Comment by ryanvergel** [comment]
I talked to @NastoohX , and he let me know that it's best to make changes elsewhere first, and then propagate them. I'm working with him now to make the changes :) Thank you!

**Pull request closed without merging**
